app/assets/stylesheets/application.scss, app/assets/stylesheets/leaflet-map.css, app/assets/stylesheets/leaflet.css, app/controllers/installations_controller.rb, app/models/submission.rb, app/views/installations/show.html.haml, db/seeds.rb
Solves: https://github.com/ContextualCamouflage/contextual-camoflage/issues/2
=> Implement Leaflet-Rails

app/models/submission.rb, db/seeds.rb, spec/controllers/submissions_controller_spec.rb
I'm going to merge this one myself since it is re-enabling a feature I already built 💃
=> Re-enable Geocoding and vary the coordinates of the submissions

app/assets/javascripts/application.js, app/assets/javascripts/submissions/resource_slider.js, app/assets/javascripts/submissions/submission_animation.js, app/assets/javascripts/theme.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/contexts/resources.scss, app/controllers/resources_controller.rb, app/views/installations/show.html.haml, app/views/resources/index.html.haml, app/views/resources/show.html.haml, config/routes.rb, spec/controllers/resources_controller_spec.rb
Set up the front end of the resource page
Uses materialize carousel (swipe compatible!) http://materializecss.com/carousel.html
Sets background color of each disorder behind the anecdote
Responsive (woo!)
Closes #10
=> #10 - Resource Pages

app/views/submissions/_story.html.haml
Changed illness submission to radio buttons
closes #24
=> Issue 24: Limit Submission to only one illness

app/assets/stylesheets/contexts/installations.scss, app/views/installations/index.html.haml
Made the installation links buttons
When not active add red class to button
closes #18
=> Issue #18 - Style index page

app/assets/javascripts/side_nav.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/contexts/navigation.scss, app/assets/stylesheets/general/font-declaration.scss, app/assets/stylesheets/general/theme.scss, app/views/layouts/application.html.haml
Add the slide nav sidebar - will probably need additional navigation pieces.
Closes #27
=> Issue #27 - SlideNav Implementation

app/assets/stylesheets/application.scss, app/assets/stylesheets/contexts/admin.scss
I put the email and password inputs into a little responsive box
Closes #19
=> Issue #19 - Style rails admin

app/models/installation.rb, config/initializers/rails_admin.rb
=> Issue #31 - Make a Tool for Adding Installation with Locality Information

app/models/submission.rb, spec/controllers/resources_controller_spec.rb, spec/models/submission_spec.rb
=> Closes Issue #41 - Do not Accept Submissions to an Inactive Installation

app/assets/stylesheets/contexts/resources.scss, app/assets/stylesheets/general/theme.scss, app/views/resources/show.html.haml
Cleaned up the styles as well
Switched both anecdote and research info background
Removed margin on main
Closes #38
=> Issue 38 - Switch anecdote with research info

app/assets/javascripts/submissions/submission_animation.js, app/views/installations/show.html.haml, app/views/submissions/_research.html.haml, config/environments/development.rb, config/environments/production.rb
Obviously select options need values to record data
---------------------------------------------------------------
Also fixes:
Adding class of index for form animation (removes js error)
Also cleaning up the submission animations and removed a submitAjax function since it was submitting research twice.
Also disabling rails 5 'feature' to disable all buttons automatically on submit. Opening a new issue to correct this in the future
=> Closes Issue #51 - Age not recording

Gemfile, Gemfile.lock, config/initializers/rollbar.rb
Rollbar provides real-time error alerting & debugging tools for developers.
=> Configure the Ruby on Rails Setup for Rollbar 💯  ✅

app/controllers/submissions_controller.rb
=> Close Issue #43 - Refactor Spam Check to Based on Session, Not Cookie

.gitignore, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/submissions/geolocate.js, app/views/submissions/_submission.html.haml
Unfortunately there is no way to check if the user has already given permission for the browser to geolocate them, so I am setting a localStorage item to check if they are authorizing the app. It's not perfect, but I think it will work most of the time.  
Closes #64
=> Geolocate user with HTML5

app/assets/stylesheets/contexts/resources.scss, app/views/resources/show.html.haml
Fixed up the padding in the resource carousel and enlarged the height to fit more text.
Added special styling for links in each carousel
Moved the go back button up so it sits always under the resource definition carousel.
Links can be clickable as long as an anchor tag is included in the db as html.
=> Closes Issue #74 - Restyle Resource pages

app/views/resources/show.html.haml
Broke because there was no anecdote and the carousel was trying to load something but couldn't (materialize issue) Added a catch to make sure there are anecdotes there before initializing the carousel div
=> Issue #78 - Hamburger menu

app/assets/javascripts/google_analytics.js, app/views/layouts/application.html.haml, config/secrets.yml
Added secret key in heroku and setup ga in the application layout
Added file to send pageviews to ga
=> Issue #52 - Setup google analytics

app/assets/stylesheets/contexts/installations.scss, app/views/installations/main.html.haml
I had created the view with the personal stories and whatever on the homepage, so i just blew all that out in favor of the map view. url is /display/[id]
=> Issue #79 - Set url to have just the map display

app/assets/javascripts/channels/map.js, app/assets/stylesheets/leaflet-map.scss, app/controllers/submissions_controller.rb
These are some juicy icons!
Changes the icons to divs with their name and background images
Added a sonar animation which iterates 2x
so juicy!
=> Juicy icons - Closes Issue #5

app/assets/stylesheets/contexts/resources.scss, app/views/resources/index.html.haml
=> Adding resources/helpful links to resource page

README.md, app/views/layouts/application.html.haml, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/routes.rb
=> Temporarily set the active Installation as the home page

app/assets/stylesheets/contexts/installations.scss
Lowering the vh of the map a bit so it all fits on the screen well
=> Aligning the share your story text and icon better

README.md
Wonderful project! I tried clicking through for more details and got a 404 - this PR fixes that.
Sadly no SSL.
=> Fix readme link to www.mckoycreative.com

README.md, app/views/layouts/application.html.haml, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/routes.rb
Reverts ContextualCamouflage/contextual-camouflage#94
The Spring Gallery Crawl is complete so we can remove this.
=> Revert "Temporarily set the active Installation as the home page"

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/initializers/is_crawler.rb
=> Solve Issue #102 - Stop Robots and Crawlers From Causing Errors in Rails
